# Generated by Django 3.2.16 on 2022-12-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20221213_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='ipaddress',
            field=models.CharField(default='1', max_length=1000),
        ),
    ]
